### ISSUE TITLE
Provide a gravity lesson

### ISSUE THREAD

**Issue by jm1021** [jm1021/alienWorld#4]
- [x] concepts
- [x] code examples
- [ ] incorporate examples with Mr L, specifically with Monkey character

**Comment by safinsingh** [comment]
Hi Mr. Mortensen,
Here is the Jupyter Notebook lesson that Rohan and I created: [https://nighthawkcoders.github.io/teacher//2023/10/12/animations-and-layers_IPYNB_2_.html](https://nighthawkcoders.github.io/teacher//2023/10/12/animations-and-layers_IPYNB_2_.html). Please let us know what you think.

**Comment by jm1021** [comment]
This is nice to see!!!   I do think the code examples would be better if we started to work toward alien world for a little more theory and structure.   We have worked hard to try to restructure a Game project into OOP.   We should talk about it today.

![image](https://github.com/jm1021/alienWorld/assets/54686997/34d2331c-25e5-4790-bb28-0222cecb54d3)

**Comment by jm1021** [comment]
FYI, notebook link in this thread is dead.

**Comment by rjawesome** [comment]
New notebook:https://nighthawkcoders.github.io/teacher//2023/10/12/animations-and-gameobjects_IPYNB_2_.html

game object and character have been separated into different js files. However, we still need to do the inheritance part.

**Comment by jm1021** [comment]
There is gravity in game now.  Perhaps a good time to figure out if we are going to do a lesson.  Or enhance gravity to match lesson.
